spring:
  datasource:
    hikari:
      write:
        jdbc-url: jdbc:h2:mem:writeDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
        username: sa
        password:
        driver-class-name: org.h2.Driver
      read:
        jdbc-url: jdbc:h2:mem:readDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
        username: sa
        password:
        driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    com:
      zaxxer:
        hikari: debug
      example:
        dbreplication: debug
    org:
      springframework: debug

